#!/bin/bash
#
# fdhtd Starts fdhtd
#
#
# chkconfig: 2345 99 01
# description: FastDHT server
### BEGIN INIT INFO
# Provides: $fdhtd
### END INIT INFO

# Source function library.
. /etc/init.d/functions

PRG=/usr/local/bin/fdhtd
CONF=/etc/fdht/fdhtd.conf

if [ ! -f $PRG ]; then
  echo "file $PRG does not exist!"
  exit 2
fi

if [ ! -f $CONF ]; then
  echo "file $CONF does not exist!"
  exit 2
fi

CMD="$PRG $CONF"
RETVAL=0

start() {
 	echo -n $"Starting fastdht server: "
	$CMD
	RETVAL=$?
	echo
	return $RETVAL
}

stop() {
    $CMD stop
	RETVAL=$?
	return $RETVAL
}

rhstatus() {
    status fdhtd
}

restart() {
   $CMD restart
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  status)
  	rhstatus
	;;
  restart|reload)
  	restart
	;;
  condrestart)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart}"
	exit 1
esac

exit $?

